[package]
name = "mimicraft2d"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
description = "A Minecraft-like 2D game built with Pygame"

[web]
name = "Mimicraft2D"
version = "0.1.0"
home = "https://sudoblank.github.io/RandomGames/"
apk = ""
icon = ""
template = "default"
cdn = "https://pygame-web.github.io/archives/0.9/"
bg_color = "#1a1a2e"
