name: Deploy Mimicraft2D to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow this workflow to deploy to Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated from v3 to v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5  # Updated from v4 to v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygbag

    - name: Build with pygbag
      run: |
        # Create a build directory and copy all necessary files
        mkdir -p build
        cp main.py build/
        cp Mimicraft2D.py build/
        cp Blockbehconfig.py build/
        cp Blocktexconfig.py build/
        cp settings.json build/
        cp pygbag.toml build/
        
        # Build the project
        cd build
        pygbag --build --title "Mimicraft2D" --app_name mimicraft --can_close true main.py

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2  # Updated from v1 to v2
      with:
        path: build/web/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3  # Updated from v2 to v3
